### ISSUE TITLE
Publish latest version on nuget

### ISSUE THREAD

**Issue by adrianhara** [GrantMegrabyan/AspNet.Identity3.MongoDB#6]
Hi guys,

Any chance you could publish the latest version for rc1 on nuget? I only seem to see beta7 there.

Thanks!

**Comment by GrantMegrabyan** [comment]
Hi,

Sorry, I completely forgot to update nuget package. It's done now.

**Comment by adrianhara** [comment]
Sweet, thanks! Awesome work btw!
