### ISSUE TITLE
UserManager.CheckPasswordAsync always return False

### ISSUE THREAD

**Issue by ashisherc** [GrantMegrabyan/AspNet.Identity3.MongoDB#9]
var user = new ApplicationUser { UserName = model.userName};
var isCorrect = await _userManager.CheckPasswordAsync(user, model.Password);

------------------  isCorrect is always False ----------------------------------------------

**Comment by GrantMegrabyan** [comment]
First you need to create user with UserManager:

``` C#
var user = new ApplicationUser { UserName = model.UserName, Email = model.Email };
var result = await _userManager.CreateAsync(user, model.Password);
```

After that this line

``` C#
var isCorrect = await _userManager.CheckPasswordAsync(user, model.Password);
```

should return correct result.

Take a look at [sample application](https://github.com/GrantMegrabyan/AspNet.Identity3.MongoDB.MvcSample) that uses this Identity system especially at [Register method in AccountController](https://github.com/GrantMegrabyan/AspNet.Identity3.MongoDB.MvcSample/blob/master/src/AspNet.Identity3.MongoDB.MvcSample/Controllers/AccountController.cs).

**Comment by ashisherc** [comment]
I tried all the way possible, provided the username, email and also id of the user from mongodatabase, tried everything separately and combined but no luck. Did some debugging with source code but could not figure out the solution.
And finally I did this

```
var user = await _userManager.FindByNameAsync(model.userName);
var isCorrect = await _userManager.CheckPasswordAsync(user,model.Password);
```

this Works fine.

**Comment by GrantMegrabyan** [comment]
I looked into source code of [Identity System](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UserManager.cs) and found out that UserManager does not assign password to user object upon creating new user. In order to have user with it password (passwordHash to be precise) you need to get user from UserManager, as you have shown in your example.

**Comment by ashisherc** [comment]
Okay, Thank you. I will close the issue.

**Comment by PeppeL-G** [comment]
I expected the code shown in the original post to work as well. A bit confusing.

**Comment by mamahmoodi** [comment]
when create user , assign value to NormalizedUserName .  .net use  Normalized Value  to work with user 

change the Code like below
var user = new ApplicationUser { UserName = model.UserName ,NormalizedUserName  = String.ToUpper( model.UserName) , Email = model.Email  ,NormalizedEmail =String.ToUpper( model.Email) };
var result = await _userManager.CreateAsync(user, model.Password);
